class_id_to_name_and_nabirds_id = {
    '0': ('529', 'Mourning Dove'),
    '1': ('553', 'Red-bellied Woodpecker'),
    '2': ('559', 'Downy Woodpecker'),
    '3': ('950', 'Blue Jay'),
    '4': ('957', 'American Crow'),
    '5': ('753', 'American Robin (Adult)'),
    '6': ('819', 'Tufted Titmouse'),
    '7': ('811', 'Carolina Chickadee'),
    '8': ('812', 'Black-capped Chickadee'),
    '9': ('824', 'White-breasted Nuthatch'),
    '10': ('830', 'Carolina Wren'),
    '11': ('902', 'Song Sparrow'),
    '12': ('889', 'Eastern Towhee'),
    '13': ('769', 'Chipping Sparrow (Breeding)'),
    '14': ('976', 'Chipping Sparrow (Immature/nonbreeding adult)'),
    '15': ('746', 'Dark-eyed Junco (Slate-colored)'),
    '16': ('764', 'White-throated Sparrow (White-striped)'),
    '17': ('796', 'House Sparrow (Male)'),
    '18': ('1003', 'House Sparrow (Female/Juvenile)'),
    '19': ('794', 'American Goldfinch (Breeding Male)'),
    '20': ('1001', 'American Goldfinch (Female/Nonbreeding Male)'),
    '21': ('790', 'House Finch (Adult Male)'),
    '22': ('997', 'House Finch (Female/immature)'),
    '23': ('772', 'Northern Cardinal (Adult Male)'),
    '24': ('979', 'Northern Cardinal (Female/Juvenile)'),
    '25': ('912', 'Common Grackle'),
    # "Red-Winged Blackbird (Female)" is omitted to avoid confusion with female sparrows/finches.
    '26': ('780', 'Red-winged Blackbird (Male)'),
    '27': ('856', 'European Starling (Nonbreeding Adult)'),
    '28': ('748', 'European Starling (Breeding Adult)'),
}
